Add dockerfile
DependableSystemsLab/LLTFI pull request #15
Opened 2022-06-16 17:34 UTC by AnushreeBannadabhavi

Initial Version of the DockerFile. Build in-progress.

2022-06-16 22:32 UTC, uditagarwal97 commented
I'm getting the following error in the dockerfile:
``` ---> cf1867d76772
Step 11/21 : RUN unzip protobuf-all-3.17.2.zip
 ---> Running in 04d0d1e1620f
/bin/sh: 1: unzip: not found
The command '/bin/sh -c unzip protobuf-all-3.17.2.zip' returned a non-zero code: 127
```

2022-06-16 22:42 UTC, AnushreeBannadabhavi commented
I'll add "RUN apt-get install unzip" in the Dockerfile. That should hopefully fix the issue. I'll also add all necessary changes in the next commit after verifying the created image.

2022-06-17 00:23 UTC, uditagarwal97 commented on docker/Dockerfile
> +WORKDIR /home/LLTFI/
WORKDIR /home/

2022-06-17 00:23 UTC, uditagarwal97 commented on docker/Dockerfile
> +  	cmake -G Ninja \
Remove the else part of this if-else condition. Command to build onnx-mlir:
``` 
cmake -G Ninja 
        -DCMAKE_CXX_COMPILER=/usr/bin/c++ 
        -DMLIR_DIR=${MLIR_DIR} 
        .. 
```

2022-06-17 00:23 UTC, uditagarwal97 commented on docker/Dockerfile
> +    cmake --build . -j 2 && \
cmake --build . -j ${nproc} && \

2022-06-17 00:23 UTC, uditagarwal97 commented on docker/Dockerfile
> +    export LIT_OPTS=-v && \
No need for this command 'LIT_OPS'

2022-06-17 00:23 UTC, uditagarwal97 commented on docker/Dockerfile
> +    cmake --build . --target check-onnx-lit && \
remove 'this command as well. Ninja install will be sufficient

2022-06-17 00:23 UTC, uditagarwal97 commented on docker/Dockerfile
> +    cd /home/LLTFI/LLTFI && \
Add command 'pip install pyyaml'

2022-06-17 00:23 UTC, uditagarwal97 commented on docker/Dockerfile
> +    ./setup -LLFI_BUILD_ROOT $(pwd)/build -LLVM_SRC_ROOT $(pwd)/../llvm-project -LLVM_DST_ROOT $(pwd)/../llvm-project/build --no_gui && \
LLVM_SRC_ROOt is wrong. it should be '$(pwd)/../../llvm_project'. same with LLVM_DST_ROOT

2022-06-18 18:30 UTC, uditagarwal97 requested changes

2022-06-18 18:30 UTC, uditagarwal97 commented on docker/Dockerfile
> +          make -j${NPROC} install \
Add a semicolon. ' make -j${NPROC} install; '

2022-06-18 18:30 UTC, uditagarwal97 commented on docker/README.md
> +- All dependencies required to build LLTFI and run sample programs and tests will be installed in the docker container built using this docker file.
Mention that the docker image does not contain dependencies for the GUI.

2022-06-18 18:30 UTC, uditagarwal97 commented on README.md
> +LLTFI is built on top of [LLFI](https://github.com/DependableSystemsLab/LLFI) and is fully backwards compatible with LLFI.
LLTFI is built on top of [LLFI](https://github.com/DependableSystemsLab/LLFI) and is fully backwards compatible with it.

2022-06-18 18:30 UTC, uditagarwal97 commented on README.md
> +  9. LLVM v13.0 (commit: 23dd750279c9) ([Reference](http://llvm.org/docs/CMake.html)).
Update the Clang and LLVM version in the README file.

2022-06-18 18:30 UTC, uditagarwal97 commented on README.md
> +			cd onnx-mlir && git checkout 221b8e1d2ad && cd ..
Use the lastest version of ONNX-MLIR

2022-06-18 18:30 UTC, uditagarwal97 commented on README.md
> +		cd llvm-project && git checkout 23dd750279c9 && cd ..
Use the latest version of LLVM

2022-06-18 18:30 UTC, uditagarwal97 commented on README.md
> +		cmake --build . --target clang check-mlir mlir-translate opt llc lli llvm-dis llvm-link
Add `-j2` flag here.

2022-06-18 18:30 UTC, uditagarwal97 commented on README.md
> +			make
Add `-j2` flag here as well

2022-06-18 18:30 UTC, uditagarwal97 commented on README.md
> +			cmake -G Ninja \
Remove the if-else condition. We only need the if part. Just like we have done in the Dockerfile.

2022-06-18 18:30 UTC, uditagarwal97 commented on README.md
> +			export LIT_OPTS=-v
Should we build the lit tests of ONNX-MLIR? If it takes too l;ong to build and run the test case, perhaps we can skip this step.

2022-06-22 19:12 UTC, AnushreeBannadabhavi commented
Addressed all the review comments in commit id '7b06e8d50ecdc4bb32b5da053fbf35a1933dbbd5'

2022-06-22 19:16 UTC, AnushreeBannadabhavi commented
Closed PR accidently

2022-06-23 13:34 UTC, uditagarwal97 approved these changes

2022-06-25 01:32 UTC, abrahamchan approved these changes
LGTM! I will go ahead and merge this as Udit also approved this too.

2022-06-25 01:32 UTC, merged